"""empty message

Revision ID: be6f8d4540a2
Revises: 7a50f649ebd6
Create Date: 2022-10-11 10:33:15.892335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6f8d4540a2'
down_revision = '7a50f649ebd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_analysis', sa.Column('fb_page', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'facebook_analysis', 'users', ['fb_page'], ['fb_page_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facebook_analysis', type_='foreignkey')
    op.drop_column('facebook_analysis', 'fb_page')
    # ### end Alembic commands ###
