"""empty message

Revision ID: d6e4d9573d7b
Revises: 7e23afb9e864
Create Date: 2022-09-04 23:47:47.069780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e4d9573d7b'
down_revision = '7e23afb9e864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_page_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fb_page_id')
    # ### end Alembic commands ###
